# Generated by Django 4.0.3 on 2022-04-21 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('kilometros', models.IntegerField()),
                ('gravedad', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_abordaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('tiempo', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Viajes.destino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.astroturista')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vehiculo', models.CharField(max_length=50)),
                ('cantidad_pasajeros', models.IntegerField()),
                ('velocidad', models.IntegerField()),
                ('precio_x_km', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pasajeros', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Viajes.destino')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Viajes.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelos_pasajeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Viajes.ticket_abordaje')),
                ('vuelos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Viajes.vuelos')),
            ],
        ),
        migrations.AddField(
            model_name='vuelos',
            name='vuelo_ticket',
            field=models.ManyToManyField(through='Viajes.Vuelos_pasajeros', to='Viajes.ticket_abordaje'),
        ),
        migrations.AddField(
            model_name='ticket_abordaje',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Viajes.vehiculo'),
        ),
    ]
