# Generated by Django 4.0.3 on 2022-04-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0002_alter_destino_gravedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelos',
            name='tiempo_viaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
