# Generated by Django 4.0.3 on 2022-04-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0003_vuelos_tiempo_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='descripcion',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
