# Generated by Django 4.0.3 on 2022-04-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0005_alter_destino_descripcion_alter_vehiculo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelos',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vuelos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen'),
        ),
        migrations.AlterField(
            model_name='vuelos',
            name='vuelo_ticket',
            field=models.ManyToManyField(blank=True, through='Viajes.Vuelos_pasajeros', to='Viajes.ticket_abordaje'),
        ),
    ]
