# Generated by Django 4.0.3 on 2022-04-29 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0006_vuelos_descripcion_vuelos_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelos',
            old_name='numero_pasajeros',
            new_name='asientos_disponibles',
        ),
        migrations.RemoveField(
            model_name='vuelos',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='vuelos',
            name='imagen',
        ),
    ]
