# Generated by Django 4.0.3 on 2022-05-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0007_rename_numero_pasajeros_vuelos_asientos_disponibles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_abordaje',
            name='codigo_qr',
            field=models.ImageField(blank=True, null=True, upload_to='imagen'),
        ),
    ]
