# Generated by Django 4.0.3 on 2022-05-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0008_ticket_abordaje_codigo_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_abordaje',
            name='distancia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vuelos',
            name='distancia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
