# Generated by Django 4.0.3 on 2022-05-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0009_ticket_abordaje_distancia_vuelos_distancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_abordaje',
            name='distancia',
        ),
        migrations.RemoveField(
            model_name='vuelos',
            name='distancia',
        ),
    ]
