# Generated by Django 4.0.3 on 2022-05-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0010_remove_ticket_abordaje_distancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='resumen',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='resumen',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destino',
            name='imagen',
            field=models.ImageField(upload_to='imagen'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(upload_to='imagen'),
        ),
    ]
