# Generated by Django 4.0.3 on 2022-05-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0011_destino_resumen_vehiculo_resumen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='precio_x_km',
            field=models.FloatField(),
        ),
    ]
