# Generated by Django 4.0.3 on 2022-05-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astroturista',
            name='avatar',
            field=models.ImageField(upload_to='avatares'),
        ),
    ]
