# Generated by Django 4.0.3 on 2022-05-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_alter_astroturista_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='astroturista',
            name='apellido',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astroturista',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astroturista',
            name='nombre',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='astroturista',
            name='peso',
            field=models.IntegerField(),
        ),
    ]
