# Generated by Django 4.0.3 on 2022-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nombre_post',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
