# Generated by Django 4.0.3 on 2022-05-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0002_comentario_likes_posts_delete_post_likes_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imagen',
            field=models.ImageField(upload_to='imagen'),
        ),
    ]
